.TH "NMEA-CHECKER" "1" "MARCH 2016" "russkubik@gmail.com" "User Manuals"
.SH "NAME"
nmea-checker \- NMEA sentence validation tool
.SH "SYNOPSIS"
\fBnmea-checker\fR [COMMAND] [\fIOPTIONS...\fR]
.SH "DESCRIPTION"
Command-line tool to validate streams of NMEA data.
.SH COMMAND
.TP
\fBvalid\fR
Validates a stream of NMEA data. Prints errors and returns statistics when done.
.br
.TP
\fBchecksum\fR
Return checksum (HEX) value of given NMEA sentences.
.br
.TP
.SH AUTHOR
nmea-checker was written by Russ Kubik <russkubik@gmail.com>.
.PP
This manual page was written by Russ Kubik <russkubik@gmail.com>
